# AI Tagging Configuration
tag.ai.enabled=true
tag.ai.base-url=https://straining-lurch-uncoiled.ngrok-free.dev

# Recommendation Service Configuration
feed.reco.enabled=true
feed.reco.base-url=https://straining-lurch-uncoiled.ngrok-free.dev
